apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-test
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: scale-test
  template:
    metadata:
      labels:
        app: scale-test
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: scale-test
            topologyKey: kubernetes.io/hostname
      nodeSelector:
        autoscale-group: workers
      containers:
      - name: httpbin
        image: mccutchen/go-httpbin:v2.15.0
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: scale-test
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerClass: binarylane.com.au/load-balancer
  selector:
    app: scale-test
  ports:
  - name: http
    port: 80
    targetPort: 8080
