# Override values for Tilt development.
# BL_API_TOKEN is set from environment in Tiltfile.
apiToken: "dev-token-replace-me"

autoscaler:
  enabled: false

externalDns:
  enabled: true
  mtls:
    enabled: true

devCleanup:
  enabled: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 256Mi
