{{- if .Values.autoscaler.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "binarylane-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "binarylane-controller.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.autoscaler.config | toJson | quote }}
  {{- if .Values.autoscaler.cloudInit }}
  cloud-init.sh: |
    {{- .Values.autoscaler.cloudInit | nindent 4 }}
  {{- end }}
{{- end }}
