{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "binarylane-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "binarylane-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  BL_API_TOKEN: {{ required "apiToken is required when existingSecret is not set" .Values.apiToken | quote }}
{{- end }}
