{{- if or .Values.autoscaler.enabled .Values.externalDns.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "binarylane-controllers.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "binarylane-controllers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.autoscaler.enabled }}
    - port: {{ include "binarylane-controllers.port" .Values.autoscaler.listenAddr }}
      targetPort: autoscaler
      protocol: TCP
      name: autoscaler
    {{- end }}
    {{- if .Values.externalDns.enabled }}
    - port: {{ include "binarylane-controllers.port" .Values.externalDns.listenAddr }}
      targetPort: external-dns
      protocol: TCP
      name: external-dns
    {{- end }}
  selector:
    {{- include "binarylane-controllers.selectorLabels" . | nindent 4 }}
{{- end }}
